media:
  input: public/images
  output: /images
content:
  - name: books
    label: Books
    type: collection
    path: src/content/books
    format: yaml-frontmatter
    filename: '{index}-{slug}.mdx'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle
        type: string
      - name: authorName
        label: Author
        type: string
        required: true
      - name: insight
        label: Insight
        type: string
        description: "One line 'senior' insight about the book"
      - name: intentTags
        label: Intent Tags
        type: select
        options:
          multiple: true
          creatable: true
        description: "List of intent tags (e.g. 'For Refactoring', 'For Architecture')"
      - name: publisher
        label: Publisher
        type: string
      - name: publicationDate
        label: Publication Date
        type: date
      - name: printLength
        label: Print Length
        type: number
      - name: amazonINLink
        label: Amazon Link
        type: string
      - name: coverImage
        label: Cover Image URL
        type: string
        description: Link to image (e.g. Amazon image URL)
      - name: description
        label: Description
        type: string
        list: true
      - name: readingStatus
        label: Reading Status
        type: select
        options:
          values: ["Currently Reading 👓","Read ✅", "Wishlisted ⭐", "Next Up ⏭️"]
      - name: recommended
        label: Recommended
        type: boolean
      - name: body
        label: Review/Notes
        type: rich-text
